#PBS -S /bin/bash
#PBS -q debug
#PBS -l mppwidth=192
#PBS -l walltime=00:30:00
#PBS -N core_sim
#PBS -e core_sim_job.$PBS_JOBID.err
#PBS -o core_sim_job.$PBS_JOBID.out
#PBS -e core_sim_job.$PBS_JOBID.err
#PBS -j oe
#PBS -A mp107
#PBS -V

cd $PBS_O_WORKDIR
export KMP_DUPLICATE_LIB_OK=TRUE
module switch PrgEnv-gnu/5.2.56 PrgEnv-intel

#aprun -n 12 -N 2 -S 1 python map_maker.py
aprun -n 32 -N 4 -S 2 python map_maker_pol.py
